name: ChatColor
version: '1.0.0'
main: me.vixxel.chatcolor.ChatColorPlugin
api-version: '1.21'
author: Vixxel
description: GUI chat color plugin

commands:
  chatcolor:
    description: Opens the ChatColor GUI
    usage: /chatcolor gui
    permission: chatcolor.gui

permissions:
  chatcolor.gui:
    description: Allows opening the chat color GUI
    default: true

  chatcolor.reload:
    description: Reload the plugin
    default: op